server:
  port: 8012

spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/rides?currentSchema=rides_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

elasticsearch:
  host: ${ES_HOST}
  promocode-index: promocodes
